-keep class com.healthsync.phone.data.model.** { *; }
-keep class com.healthsync.phone.data.update.** { *; }
-keep class com.healthsync.phone.data.watchface.** { *; }
-keepclassmembers class com.healthsync.phone.data.update.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken { *; }
-dontwarn com.github.mikephil.charting.**
